//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumpahRasa_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comment
    {
        public int id_comment { get; set; }
        public int id_member { get; set; }
        public int id_recipe { get; set; }
        public string comment { get; set; }
        public int rating { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual tb_member tb_member { get; set; }
        public virtual tb_recipe tb_recipe { get; set; }
        public virtual tb_recipe tb_recipe1 { get; set; }
    }
}
