//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumpahRasa_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tb_recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_recipe()
        {
            this.tb_comment = new HashSet<tb_comment>();
            this.tb_comment1 = new HashSet<tb_comment>();
            this.tb_loved = new HashSet<tb_loved>();
            this.tb_loved1 = new HashSet<tb_loved>();
        }
    
        public int id_recipe { get; set; }

        public string name { get; set; }

        public string thumbnail { get; set; }

        [AllowHtml]
        public string description { get; set; }

        public Nullable<System.DateTime> created_at { get; set; }

        public Nullable<int> id_admin { get; set; }

        public Nullable<double> rating { get; set; }
    
        public virtual tb_admin tb_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comment> tb_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comment> tb_comment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_loved> tb_loved { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_loved> tb_loved1 { get; set; }
    }
}
